[project]
name = "sft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.5.0",
    "torch>=2.6.0",
    "transformers>=4.51.2",
    "trl>=0.16.1",
]
